/**
 * Autogenerated by AIngle
 *
 * DO NOT EDIT DIRECTLY
 */
package aingle.examples.baseball;

/** This is protocol */
@org.apache.aingle.specific.AIngleGenerated
public interface Proto {
  public static final org.apache.aingle.Protocol PROTOCOL = org.apache.aingle.Protocol.parse("{\"protocol\":\"Proto\",\"namespace\":\"aingle.examples.baseball\",\"doc\":\"This is protocol\",\"types\":[],\"messages\":{\"bar\":{\"doc\":\"method 'bar' does nothing */\",\"request\":[],\"response\":\"null\"}}}");
  /**
   * method 'bar' does nothing *&#47;
   */
  void bar();

  /** This is protocol */
  @org.apache.aingle.specific.AIngleGenerated
  public interface Callback extends Proto {
    public static final org.apache.aingle.Protocol PROTOCOL = aingle.examples.baseball.Proto.PROTOCOL;
    /**
     * method 'bar' does nothing *&#47;
     * @throws java.io.IOException The async call could not be completed.
     */
    void bar(org.apache.aingle.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}