// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by ainglegen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.apache.aingle.test
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using AIngle;
	using AIngle.Specific;
	
	public partial class FixedTest : SpecificFixed
	{
		private static Schema _SCHEMA = AIngle.Schema.Parse("{\"type\":\"fixed\",\"name\":\"FixedTest\",\"namespace\":\"org.apache.aingle.test\",\"size\":10}");
		private static uint fixedSize = 10;
		public FixedTest() :
				base(fixedSize)
		{
		}
		public override Schema Schema
		{
			get
			{
				return FixedTest._SCHEMA;
			}
		}
		public static uint FixedSize
		{
			get
			{
				return FixedTest.fixedSize;
			}
		}
	}
}
