// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by ainglegen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.apache.aingle.test
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using AIngle;
	using AIngle.Specific;
	
	public abstract class Mail : AIngle.Specific.ISpecificProtocol
	{
		private static readonly AIngle.Protocol protocol = AIngle.Protocol.Parse(@"{
  ""protocol"": ""Mail"",
  ""namespace"": ""org.apache.aingle.test"",
  ""types"": [
    {
      ""type"": ""record"",
      ""name"": ""Message"",
      ""namespace"": ""org.apache.aingle.test"",
      ""fields"": [
        {
          ""name"": ""to"",
          ""type"": ""string""
        },
        {
          ""name"": ""from"",
          ""type"": ""string""
        },
        {
          ""name"": ""body"",
          ""type"": ""string""
        }
      ]
    }
  ],
  ""messages"": {
    ""send"": {
      ""request"": [
        {
          ""name"": ""message"",
          ""type"": ""Message""
        }
      ],
      ""response"": ""string""
    },
    ""fireandforget"": {
      ""request"": [
        {
          ""name"": ""message"",
          ""type"": ""Message""
        }
      ],
      ""response"": ""null"",
      ""one-way"": true
    }
  }
}");
		public AIngle.Protocol Protocol
		{
			get
			{
				return protocol;
			}
		}
		public void Request(AIngle.Specific.ICallbackRequestor requestor, string messageName, object[] args, object callback)
		{
			switch(messageName)
			{
				case "send":
				requestor.Request<System.String>(messageName, args, callback);
				break;

				case "fireandforget":
				requestor.Request<System.Object>(messageName, args, callback);
				break;
			};
		}
		public abstract string send(org.apache.aingle.test.Message message);
		public abstract void fireandforget(org.apache.aingle.test.Message message);
	}
}
