// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by ainglegen.vshost.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.apache.aingle.test
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using AIngle;
	using AIngle.Specific;
	
	public partial class MD5 : SpecificFixed
	{
		private static Schema _SCHEMA = AIngle.Schema.Parse("{\"type\":\"fixed\",\"name\":\"MD5\",\"namespace\":\"org.apache.aingle.test\",\"size\":16,\"javaAn" +
				"notation\":\"org.apache.aingle.TestAnnotation\"}");
		private static uint fixedSize = 16;
		public MD5() :
				base(fixedSize)
		{
		}
		public override Schema Schema
		{
			get
			{
				return MD5._SCHEMA;
			}
		}
		public static uint FixedSize
		{
			get
			{
				return MD5.fixedSize;
			}
		}
	}
}
