/*

 */

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.IO.Stream)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.IO.Stream,System.Boolean)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.IO.Stream,AIngle.Schema)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.IO.Stream,AIngle.Schema,System.Boolean)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.IO.Stream,AIngle.Schema,AIngle.File.DataFileReader`1.CreateDatumReader`0)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.IO.Stream,AIngle.Schema,AIngle.File.DataFileReader`1.CreateDatumReader`0,System.Boolean)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.String)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.OpenReader(System.String,AIngle.Schema)~AIngle.File.IFileReader{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenWriter(AIngle.Generic.DatumWriter{`0},System.IO.Stream)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenWriter(AIngle.Generic.DatumWriter{`0},System.IO.Stream,System.Boolean)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenWriter(AIngle.Generic.DatumWriter{`0},System.IO.Stream,AIngle.File.Codec)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenWriter(AIngle.Generic.DatumWriter{`0},System.IO.Stream,AIngle.File.Codec,System.Boolean)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenWriter(AIngle.Generic.DatumWriter{`0},System.String)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenWriter(AIngle.Generic.DatumWriter{`0},System.String,AIngle.File.Codec)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenAppendWriter(AIngle.Generic.DatumWriter{`0},System.String)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.File.DataFileWriter`1.OpenAppendWriter(AIngle.Generic.DatumWriter{`0},System.IO.Stream,System.IO.Stream)~AIngle.File.IFileWriter{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Purposely catch any exception", Scope = "member", Target = "~M:AIngle.File.DataFileReader`1.Sync(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Purposely catch any exception", Scope = "member", Target = "~M:AIngle.Specific.ObjectCreator.FindType(System.String)~System.Type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Purposely catch any exception", Scope = "member", Target = "~M:AIngle.Specific.ObjectCreator.GetType(AIngle.Schema)~System.Type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Maintain public API", Scope = "member", Target = "~F:AIngle.CodeGen.namespaceLookup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Maintain public API", Scope = "member", Target = "~F:AIngle.Generic.GenericFixed.value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Maintain public API", Scope = "member", Target = "~F:AIngle.Field.aliases")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Maintain public API", Scope = "member", Target = "~F:AIngle.Field.Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "Maintain public API", Scope = "member", Target = "~P:AIngle.EnumSchema.Item(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "Maintain public API", Scope = "member", Target = "~P:AIngle.Protocol.MD5")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.Schema.GetTypeString(AIngle.Schema.Type)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Maintain public API", Scope = "member", Target = "~P:AIngle.UnnamedSchema.Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1721:Property names should not match get methods", Justification = "Maintain public API", Scope = "member", Target = "~M:AIngle.NamedSchema.GetName(Newtonsoft.Json.Linq.JToken,System.String)~AIngle.SchemaName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1721:Property names should not match get methods", Justification = "Maintain public API", Scope = "member", Target = "~P:AIngle.NamedSchema.Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1724:Type names should not match namespaces", Justification = "Reviewed", Scope = "type", Target = "~T:AIngle.Schema")]
