// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by ainglegen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.foo
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using AIngle;
	using AIngle.Specific;
	
	public partial class A : ISpecificRecord
	{
		public static Schema _SCHEMA = AIngle.Schema.Parse("{\"type\":\"record\",\"name\":\"A\",\"namespace\":\"com.foo\",\"fields\":[{\"name\":\"f1\",\"type\":\"" +
				"long\"}]}");
		private long _f1;
		public virtual Schema Schema
		{
			get
			{
				return A._SCHEMA;
			}
		}
		public long f1
		{
			get
			{
				return this._f1;
			}
			set
			{
				this._f1 = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.f1;
			default: throw new AIngleRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.f1 = (System.Int64)fieldValue; break;
			default: throw new AIngleRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
