// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by ainglegen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.foo
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using AIngle;
	using AIngle.Specific;
	
	public enum MyEnum
	{
		A,
		B,
		C,
	}
}
