# frozen_string_literal: true
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# 
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'rubygems'
require 'echoe'
VERSION = File.open('../../share/VERSION.txt').read.sub('-SNAPSHOT', '.pre1').chomp
File.write("lib/aingle/VERSION.txt", VERSION)
Echoe.new('aingle', VERSION) do |p|
  p.author = "AInlge dev Team"
  p.email = "carlos.tovar@blockinnovation.center"
  p.summary = "Apache AIngle for Ruby"
  p.description = "AIngle is a data serialization and RPC format"
  p.url = "https://apache.aingle.ai/"
  p.runtime_dependencies = ["multi_json ~>1"]
  p.licenses = ["Apache-2.0"]
end

t = Rake::TestTask.new(:interop)
t.pattern = 'interop/test*.rb'

task :generate_interop do
  $:.unshift(HERE + '/lib')
  $:.unshift(HERE + '/test')
  require 'aingle'
  require 'random_data'

  schema = AIngle::Schema.parse(File.read(SCHEMAS + '/interop.ain'))
  r = RandomData.new(schema, ENV['SEED'])
  AIngle::DataFile.codecs.each do |name, codec|
    next unless codec
    filename = name == 'null' ? 'ruby.aingle' : "ruby_#{name}.aingle"
    path = File.join(BUILD, 'interop/data', filename)
    AIngle::DataFile.open(path, 'w', schema.to_s, name) do |writer|
      writer << r.next
    end
  end
end


HERE = File.expand_path(File.dirname(__FILE__))
SHARE = HERE + '/../../share'
SCHEMAS = SHARE + '/test/schemas'
BUILD = HERE + '/../../build'

task :dist => [:gem] do
  mkdir_p "../../dist/ruby"
  cp "pkg/aingle-#{VERSION}.gem", "../../dist/ruby"
end
