

name: 'Test Python'
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - .github/workflows/test-lang-py.yml
    - lang/py/**

defaults:
  run:
    working-directory: lang/py

jobs:
  test:
    name: Python ${{ matrix.python }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
        - '3.9'
        - '3.8'
        - '3.7'
        - '3.6'
        - 'pypy-3.7'
        - 'pypy-3.6'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Apt Install Compression Libs
        run: |
          sudo apt-get install -qqy --no-install-recommends libbz2-dev \
                                                            libjansson-dev \
                                                            liblzma-dev \
                                                            libsnappy-dev \
                                                            libzstd-dev

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools tox-wheel

      - name: Lint
        if: ${{ matrix.python == '3.9' }}
        run: python3 -m tox -e lint

      - name: Typechecks
        if: ${{ matrix.python == '3.9' }}
        run: python3 -m tox -e typechecks

      - name: Test
        run: python3 -m tox -e py

  interop:
    name: Python ${{ matrix.python }} Interop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
        - '3.9'
        - '3.8'
        - '3.7'
        - '3.6'
        - 'pypy-3.7'
        - 'pypy-3.6'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Apt Install Compression Libs
        run: |
          sudo apt-get install -qqy --no-install-recommends libbz2-dev \
                                                            libjansson-dev \
                                                            liblzma-dev \
                                                            libsnappy-dev \
                                                            libzstd-dev

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools tox-wheel
          python3 -m pip install python-snappy zstandard

      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Java AIngle for Interop Test
        working-directory: .
        run: mvn -B install -DskipTests

      - name: Create Interop Data Directory
        working-directory: .
        run: mkdir -p build/interop/data

      - name: Generate Interop Resources
        working-directory: lang/java/aingle
        run: mvn -B -P interop-data-generate generate-resources

      - name: Generate Interop Data
        run: ./build.sh interop-data-generate

      - name: Run Interop Tests
        run: ./build.sh interop-data-test
