

name: 'Test Java'
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - .github/workflows/test-lang-java.yml
    - lang/java/**
    - pom.xml

defaults:
  run:
    working-directory: lang/java

jobs:
  test:
    name: Java ${{ matrix.java }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - '8'
        - '11'
    steps:
      - uses: actions/checkout@v2

      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Lint
        run: ./build.sh lint

      - name: Test
        run: ./build.sh test

  interop:
    name: Java ${{ matrix.java }} Interop
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - '8'
        - '11'
    steps:
      - uses: actions/checkout@v2

      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Install Java AIngle for Interop Test
        working-directory: .
        run: mvn -B install -DskipTests

      - name: Create Interop Data Directory
        working-directory: .
        run: mkdir -p build/interop/data

      - name: Generate Interop Resources
        working-directory: lang/java/aingle
        run: mvn -B -P interop-data-generate generate-resources

      - name: Run Interop Tests
        working-directory: lang/java/ipc
        run: mvn -B test -P interop-data-test
